# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4d95406237b8f569a6144ccd7894c975490ba463732ef9a623c17918baf76d45c37227880aaef0c2c64a875d770b59b48f134e1df2a5a74179ff961b027cd71

test:
  secret_key_base: e5d8a220291802ab74001d72bbd20c13157772dbe432e8c02983cee36c56911a618a4d3604f7331a3591fe3b109971939c284a0577b1270c83bef61bc888dd91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
